FORMAT: 1A
HOST: http://catsgalore.apiblueprint.org/

# catsgalore

Cats Galore API is a simple API allowing consumers to view cats by breeds, adoptables, and organizations 

## Breed Collection [/breeds{?page,page_size}]

+ Parameters
    + page (number, optional) - page number in the form of an integer 
        + Default: `0`
    + page_size (number, optional) - page size in the form of an integer
        + Default: `5`

### List All Breeds [GET]

+ Response 200 (application/json)

        [
            {
                "id": 2345,
                "breed": "Abyssinian",
                "type": "natural",
                "size": "medium",
                "weight": "(7.5 to 16)lb (pounds)",
                "personality": ["active", "affectionate", "agenda-driven", "busy", "curious", "intelligent", "interactive", "loyal", "playful", "social"],
                "hair_length": ["medium", "short"],
                "origin": "Egypt",
                "description": ["Medium-sized and muscular cat with a ticked coat and the general appearance of a mountain lion", "Coat appears iridescent due to its agouti ticking, with bands of color on each hair", "Also exists in a Somali variety, which has a  longer coat and furnishings on its ears and tail", "Large eyes are surrounded by dark &quot;eyeliner&quot; and then another ring of lighter color"],
                "temperament": ["active", "affectionate", "agenda-driven", "busy", "curious", "intelligent", "interactive", "loyal", "playful", "social"],
                "history": ["Developed in Egypt in the mid-19th century, despite the reference in the breed&apos;s name to Ethiopia, and ay descend from cats depicted in ancient Egyptian art", "Further developed in Great Britain after being brought by soldiers", "Known in the United States since first being shown there in 1909, and grew in popularity during the 1930s"],
                "recognitions": ["The Cat Fanciers&apos; Association, Inc.  (CFA)", "The International Cat Association  (TICA)", "The Governing Council of the Cat Fancy  (GCCF)", "Fédération Internationale Féline  (FIFe)"],
                "wiki_link": "http://en.wikipedia.org/wiki/Abyssinian_(cat)",
                "images": ["http://images6.fanpop.com/image/photos/33400000/Cute-Cats-cats-33440930-1280-800.jpg"]
        
            }
        ]

        
## Breed [/breeds/{breed_id}]
        
+ Parameters
    + breed_id (number) - ID of the breed in the form of an integer

### Breed Information [GET]

+ Response 200 (application/json)

        {
            "id": 2345,
            "breed": "Abyssinian",
            "type": "natural",
            "size": "medium",
            "weight": "(7.5 to 16)lb (pounds)",
            "personality": ["active", "affectionate", "agenda-driven", "busy", "curious", "intelligent", "interactive", "loyal", "playful", "social"],
            "hair_length": ["medium", "short"],
            "origin": "Egypt",
            "description": ["Medium-sized and muscular cat with a ticked coat and the general appearance of a mountain lion", "Coat appears iridescent due to its agouti ticking, with bands of color on each hair", "Also exists in a Somali variety, which has a  longer coat and furnishings on its ears and tail", "Large eyes are surrounded by dark &quot;eyeliner&quot; and then another ring of lighter color"],
            "temperament": ["active", "affectionate", "agenda-driven", "busy", "curious", "intelligent", "interactive", "loyal", "playful", "social"],
            "history": ["Developed in Egypt in the mid-19th century, despite the reference in the breed&apos;s name to Ethiopia, and ay descend from cats depicted in ancient Egyptian art", "Further developed in Great Britain after being brought by soldiers", "Known in the United States since first being shown there in 1909, and grew in popularity during the 1930s"],
            "recognitions": ["The Cat Fanciers&apos; Association, Inc.  (CFA)", "The International Cat Association  (TICA)", "The Governing Council of the Cat Fancy  (GCCF)", "Fédération Internationale Féline  (FIFe)"],
            "wiki_link": "http://en.wikipedia.org/wiki/Abyssinian_(cat)",
            "images": ["http://images6.fanpop.com/image/photos/33400000/Cute-Cats-cats-33440930-1280-800.jpg"]

        }


## Adobtables Collection [/adoptables{?page,page_size}]

+ Parameters
    + page (number, optional) - page number in the form of an integer 
        + Default: `0`
    + page_size (number, optional) - page size in the form of an integer
        + Default: `5`

### List All Adoptabes [GET]

+ Response 200 (application/json)

        [
            {
                "id": 45678,
                "org_id": 7890,
                "name": "marcos",
                "breed": "siamese",
                "breed_id" : 1985,
                "mixed": "No",
                "age": "Baby",
                "sex": "Male",
                "weight": "5 pounds",
                "images": ["http://images6.fanpop.com/image/photos/33400000/Cute-Cats-cats-33440930-1280-800.jpg"]
            }
        ]


## Adoptable [/adoptables/{adoptable_id}]

+ Parameters
    + adoptable_id (number) - ID of the breed in the form of an integer

### Adoptable Information [GET]

+ Response 200 (application/json)

        {
            "id": 45678,
            "org_id": 7890,
            "name": "marcos",
            "breed": "siamese",
            "breed_id" : 1985,
            "mixed": "No",
            "age": "Baby",
            "sex": "Male",
            "weight": "5 pounds",
            "images": ["http://images6.fanpop.com/image/photos/33400000/Cute-Cats-cats-33440930-1280-800.jpg"]
        }


## Adoptables Breed Collection [/adoptables/{breed_id}{?page,page_size}]

+ Parameters
    + breed_id (number) - ID of the breed in the form of an integer
    + page (number, optional) - page number in the form of an integer 
        + Default: `0`
    + page_size (number, optional) - page size in the form of an integer
        + Default: `5`

### List All Adoptabes of a given breed [GET]

+ Response 200 (application/json)

        [
            {
                "id": 45678,
                "org_id": 7890,
                "name": "marcos",
                "breed": "siamese",
                "breed_id" : 1985,
                "mixed": "No",
                "age": "Baby",
                "sex": "Male",
                "weight": "5 pounds",
                "images": ["http://images6.fanpop.com/image/photos/33400000/Cute-Cats-cats-33440930-1280-800.jpg"]
            }
        ]
   
        
## Adoptables Organization Collection [/adoptables/{org_id}{?page,page_size}]

+ Parameters
    + org_id (number) - ID of the organization in the form of an integer
    + page (number, optional) - page number in the form of an integer 
        + Default: `0`
    + page_size (number, optional) - page size in the form of an integer
        + Default: `5`

### List All Adoptabes of a given organization [GET]

+ Response 200 (application/json)

        [
            {
                "id": 45678,
                "org_id": 7890,
                "name": "marcos",
                "breed": "siamese",
                "breed_id" : 1985,
                "mixed": "No",
                "age": "Baby",
                "sex": "M",
                "size": "S",
                "images": ["http://images6.fanpop.com/image/photos/33400000/Cute-Cats-cats-33440930-1280-800.jpg"]
            }
        ]
        
## Organization Collection [/organizations{?page,page_size}]

+ Parameters
    + page (number, optional) - page number in the form of an integer 
        + Default: `0`
    + page_size (number, optional) - page size in the form of an integer
        + Default: `5`

### List All Organizations [GET]

+ Response 200 (application/json)

        [
            {
                "id": 45678,
                "name": "Catastic",
                "address1": "123 Cat Lane",
                "address2": "",
                "city": "Seattle",
                "state": "Washington",
                "zip": "98101",
                "country": "United States",
                "latitude": 47.6,
                "longitude": 122.33,
                "phone": "(281) 330-8004",
                "fax": "(281) 373-9384",
                "email": "cutecats@catastic.com"
            }
        ]
        
## Organization [/organizations/{org_id}]

+ Parameters
    + org_id (number) - ID of the organization in the form of an integer

### Organization information [GET]

+ Response 200 (application/json)

        {
            "id": 45678,
            "name": "Catastic",
            "address1": "123 Cat Lane",
            "address2": "",
            "city": "Seattle",
            "state": "Washington",
            "zip": "98101",
            "country": "United States",
            "latitude": 47.6,
            "longitude": 122.33,
            "phone": "(281) 330-8004",
            "fax": "(281) 373-9384",
            "email": "cutecats@catastic.com"
        }